name: Daily Usage Reset

on:
  # ⏰ Runs automatically every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # 🧪 Allows manual testing in GitHub’s UI
  workflow_dispatch:

jobs:
  call-reset-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Nana Kick usage reset API
        run: |
          curl -X POST https://vercel.com/travis-parks-projects/nana-kick/BRMfPqZ2h9RaU9fKshUcucY13z2J \
            -H "x-cron-secret: ${{ secrets.USAGE_CRON_SECRET }}"